---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: l4t

resources:
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/route.yaml

patches:
- target:
    kind: Route
  patch: |-
    - op: replace
      path: /spec/host
      value: repo-l4t.apps.okd.jharmison.com
